### PR TITLE
Add default constructor and open() method

### PR DESCRIPTION
**Pull request by kirillin**
Sometimes a separate open method is vital.

### CODE REVIEW

**Comment by SRombauts** [comment]
Hello, thanks for this!

Have you noticed CI complains about a lesser code coverage with your change? 
It would be because you don't test all the new code paths. 

I am quite reluctant to have this change; it modifies a lot the behavior/semantic od the Database object...  It needs more thinking, as well as more testing 

Also, your default constructor should really Initialize all variables.

**Comment by SRombauts** [comment]
About the test coverage decrease, you would need to test all cases in the new Database::open() method
(see edit: https://coveralls.io/builds/27254814/source?filename=src/Database.cpp)

But actually, it would be a lot better to have my old constructor call this new open method itself, so you would not need any more unit tests, it would be covered by specific existing ones

**Comment by SRombauts** [comment]
See also #103 dynamically create 'DB' item and use it until close

**Comment by tzpeng** [comment]
//Add close() method
//Fix sqlite3_close sometimes return SQLITE_BUSY
int ret = sqlite3_close(db); 
while (ret == SQLITE_BUSY) {
	ret = SQLITE_OK;
	
	sqlite3_stmt *stmt = sqlite3_next_stmt(db, NULL);
	if (stmt != NULL) {
		ret = sqlite3_finalize(stmt);
		if (ret == SQLITE_OK) {
			ret = sqlite3_close(db);
		}
	}
}

**Pull request closed without merging**
