### PR TITLE
Added tryExecuteStep and tryReset

### LINKED ISSUE #121: Statement executeStep and reset with return code instead of throwing?
Hi! Thanks for developing this library, it has really made it super easy to use sqlite with c++

Would it be possible add alternatives to executeStep and reset in Statement which do not throw exceptions but instead lets me handle the error code? I need this since I want to ignore foreign key violations.

Currently I need to use two try statements (one for executeStep and one for reset) and this makes the code look really ugly (not to mention the performance impact of throwing and catching two exceptions)

Currently I'm doing something like this:
```
SQLite::Statement insertStmt(db, "INSERT OR IGNORE INTO...");

for (const auto &obj : objects) {

    //Bind obj to stmt...

    try {
        insertStmt.executeStep();
    } catch (SQLite::Exception &ex) {
        if (ex.getExtendedErrorCode() != SQLITE_CONSTRAINT_FOREIGNKEY) {
            throw;
        }
    }

    try {
        insertStmt.reset();
    } catch (SQLite::Exception &ex) {
        if (ex.getExtendedErrorCode() != SQLITE_CONSTRAINT_FOREIGNKEY) {
            throw;
        } else {
            continue;
        }
    }

    //Do more stuff if insert was successful
}

```

### PR DESCRIPTION
**Pull request by kaptenhonek**
fixes #121

### CODE REVIEW

**Comment by SRombauts** [comment]
Great @kaptenhonek, thanks for your work on this!

I'll have a look at your code, but could you provide a basic unit test so that the code coverage does not decrease?

Cheers!

**Comment by kaptenhonek** [comment]
Sure!

**Comment by kaptenhonek** [comment]
Added tests (basically copied and adapted the test for executeStatement)

**Comment by SRombauts** [comment]
Hi @kaptenhonek, thanks again. I've added two commits on (my copy of) your branch (see references above).

It mainly uses mbDone to return a SQLITE_MISUSE as was done previously with exceptions.

If it's okay for you, I'll merge it as is.

**Comment by kaptenhonek** [comment]
Yeah, my initial commits was done quickly just to get things working, thanks for correcting the code :)
Should I close this merge request? (after you merge your changes)

**Comment by SRombauts** [comment]
You did perfectly find!

I had to review the code, because it was getting too big/ugly, but this is just normal process.

Thanks you again!

**Comment by SRombauts** [comment]
Also, the merge-request has been closed automatically by the merge commit I pushed, AND the issue was closed since you referenced it in your first comment :)

**Comment by kaptenhonek** [comment]
Awesome, thanks and good job :)

**Pull request merged**
