### PR TITLE
Fix cmake scoping issues with packaged SQLite

### PR DESCRIPTION
**Pull request by peterbell10**
Linking against the packaged version of `sqlite3` only added include paths when installed, not during build, due to being included as `PRIVATE`. I assume this was done because `SQLiteCpp` users shouldn't need to include `sqlite.h`, so I've  also changed `SQLiteCpp` to link privately to `sqlite`.

Now `sqlite` correctly propagates its include directory when linked, but it is not propagated to users linking against `SQLiteCpp`. These changes are useful because internal and external sqlite now behave the same.

### CODE REVIEW

**Comment by sum01** [comment]
I believe the `find_dependency(SQLite3 REQUIRED)` call in `cmake/SQLiteCppConfig.cmake.in` should also be removed when doing this.

**Comment by peterbell10** [comment]
IIUC, I think it's still required. Private dependencies still need to be linked transitively when built as shared libs. So, the installed cmake still depends on sqlite3.

**Comment by SRombauts** [comment]
Hello, thank you for this proposal. 

I think it's actually thé opposite that we want: users sometimes need to include sqlite.h themselves when they want access to any C function that is not wrapped here

**Comment by peterbell10** [comment]
Okay, I was just going for consistency with how it worked already. I've reversed the private linking.

**Comment by SRombauts** [comment]
Yes, I understand, no worries :)

This CMake code has changed a lot recently, and a big part of its features are not tested.

I am a strong believer that only the automatically tested features can be properly maintained!
So I'll try to implement a few basic examples of usage of SQLiteCpp

**Comment by nidefawl** [comment]
Any progress on this?
Using SQLiteCpp with find_package has been broken for almost 2 years now.
See https://github.com/SRombauts/SQLiteCpp/issues/276

**Comment by SRombauts** [comment]
Hey @peterbell10, I am so sorry, I intended to finally try to merge this one and test everything but it is no in conflict

**Comment by SRombauts** [comment]
Hey, thanks a lot for providing this; I am now going to finally give it a go!

**Pull request merged**
