### PR TITLE
Add OPEN_FULLMUTEX flag into Database.h file

### PR DESCRIPTION
**Pull request by rwrx**
I am really sorry, I have forgot to add OPEN_FULLMUTEX as extern into Database.h file. Is it possible to merge it into release 3.1.0?

### CODE REVIEW

**Comment by SRombauts** [comment]
I'll do a quick release asap, please remind me if I take too long

**Comment by rwrx** [comment]
Thank you a lot. I am just reminding.

**Comment by rwrx** [comment]
Hello @SRombauts I just have a question if you will do this small release. Thank you.

**Comment by SRombauts** [comment]
Hello @rwrx here you are https://github.com/SRombauts/SQLiteCpp/releases

Cheers!

**Comment by rwrx** [comment]
Thank you a lot.

**Pull request merged**
