### PR TITLE
add tuple bind

### PR DESCRIPTION
**Pull request by maxbachmann**
added the option to use a tuple with values to bind.
I will use this to implement executeMany as described in  #24, so it will be possible to pass multiple tuples

I only created this PR, so the CI already tests this, since I still need to implement executemany and add some tests

### CODE REVIEW

**Comment by maxbachmann** [comment]
I did not test this at all yet, so I guess it should work, but I definetly need to write a unit test for these functions aswell and add some comments. However when there is already something you would do in a different way feel free to comment on it ;)

**Comment by maxbachmann** [comment]
@SRombauts I added test cases, comments and fixed a few broken things, so now it should be ready for review and integration

**Comment by maxbachmann** [comment]
@SRombauts little reminder :)

**Comment by SRombauts** [comment]
Thank you very much for this contribution!

I was very busy recently (releasing a pre alpha version of a game) but I will try to also review and merge the few other interesting PR waiting.

Cheers!

**Pull request merged**
