### PR TITLE
Change paths in example1 to absolute

### PR DESCRIPTION
**Pull request by kartikkumar**
Hi,

After constantly seeing the example failing when I run make test, I decided to try and fix it. I've now added a little helper function that returns the absolute path to the example1 sub-directory. This is then tagged onto the filenames for the db and logo, so that they can be referenced in an absolute sense.

Works for me on Mac OS X 10.10 and Ubuntu 14.04.

Hope this is useful.

### CODE REVIEW

**Comment by SRombauts** [comment]
Hi, thank you, but I cannot find any commit from you in your pull request; seems to me that you made a small mistake ;)

**Comment by kartikkumar** [comment]
Ok, so looks like once you've created a pull request, you can't remove the comparison branch :)

So I've put the commit back in the branch on my fork. You should see the diff now since I can see it.

**Comment by kartikkumar** [comment]
Strangely, even though `git diff` confirms that the online difference between upstream master and the branch in my fork are changes to `examples/example1/main.cpp`, it shows 3 other files modified in this pull request. Don't know what's causing that, but the only changes I'm suggesting are in the `examples/example1/main.cpp` file.

**Comment by SRombauts** [comment]
Hi, I forgot to tell you that I cherry-pick your commit instead of merging your branch; there was those 3 extra commits on it.

And as a clean cherry-pick, you are still credited for the fix :)

Thanks again!

**Comment by kartikkumar** [comment]
Thanks for the merge!

**Pull request closed without merging**
