### PR TITLE
Create Meson CI

### PR DESCRIPTION
**Pull request by ninjaoflight**
PR that completes #403, adding the base meson CI pipeline

### CODE REVIEW

**Comment by ninjaoflight** [comment]
getting (`0xC0000139`) on both `Windows MSVC` and `Windows Clang`, which appears to be the same `DLL not found`. I think it's the same `MinGW` error from #384, need to check this later and check which DLLs are missing

**Comment by ninjaoflight** [comment]
> getting (`0xC0000139`) on both `Windows MSVC` and `Windows Clang`, which appears to be the same `DLL not found`. I think it's the same `MinGW` error from #384, need to check this later and check which DLLs are missing

seems that the sqlite3.dll was not found, managed to fix it by building it instead via `--force-fallback-for=sqlite3`

**Comment by ninjaoflight** [comment]
fixed the macOS CI error by using the fallback SQLite3

**Comment by ninjaoflight** [comment]
Fixed Clang errors by fixing the setup of environment variables, as for MSVC used a task that enabled the automatic discovery of MSVC

**Comment by SRombauts** [comment]
Thanks a lot for all this! God job

**Pull request merged**
