### PR TITLE
Appveyor + Sqlite update

### PR DESCRIPTION
**Pull request by MariadeAnton**
Includes:

- Update to sqlite v3.8.8.2
- Appveyor CI file to build with Visual Studio 12
- Added README badges for biicode and Appveyor
- Minor updates on CMakeLists.txt and biicode.conf file

### CODE REVIEW

**Comment by MariadeAnton** [comment]
Have you checked this? thanks!

**Comment by SRombauts** [comment]
Hi @MariadeAnton, sorry for the delay!

I have already taken some time to review the proposed changes, and this a few time some while ago... 
But I must admit I don't like merging so much different subjects / different files in one shot.

So instead of waiting more, or closing this, let me propose the following:
Can you please split it in at least 2 pull requests?
1) biicode updates : I will take them directly (also I don't like the ALL UPPER CASE syntax, but why not)
2) update to sqlite 3.8.8.3 : thats also okay
3) Appveyor file : I will certainly do it all myself in time, to make it more simple

Again, sorry for the time it took me to acknowledge your work!
Cheers!

**Comment by MariadeAnton** [comment]
Sure, I get that :) - I'll split them asap and remove the appveyor file. 

Thanks!

**Comment by SRombauts** [comment]
Thanks to you for your patience!

Le ven. 20 mars 2015 18:59, María de Antón <notifications@github.com> a
écrit :

**Comment by MariadeAnton** [comment]
Opened 2 PR to split things.

**Pull request closed without merging**
