### PR TITLE
Link libssp when targetted

### PR DESCRIPTION
**Pull request by Asriwi**
Please let me know if this PR is redundant, it fixes the following issue for me however using MSYS2 and g++. 

The condition

```
else (MSVC)
...
    add_compile_options(-fstack-protector -Wall -Winit-self -Wswitch-enum -Wshadow -Winline)
...
endif (MSVC)
```

enforces `-fstack-protector`. Any library linking SQLiteCpp then requires libssp, so I have added a `target_link_libraries` to the CMakeLists.txt file to support this.

### CODE REVIEW

**Comment by Asriwi** [comment]
Closed as this caused build issues, it's probably more sensible to deal with this in the project targetting SQLiteCpp.

**Comment by Asriwi** [comment]
For any who might read this, I fixed this with the following addition to my CMakeLists.txt.

```
if (UNIX)
    target_link_libraries( <name> pthread )
    if (NOT APPLE)
        target_link_libraries( <name> dl )
    endif ()
elseif (MSYS)
    target_link_libraries( <name> ssp )
endif ()
```

**Comment by SRombauts** [comment]
Hi @Asriwi, thanks for reporting this!

Could you update this Merge Request with the code you are using?

Also, I should really update the AppVeyor continuous integration build script to add build for MSYS and MINGW...

Cheers!

**Comment by Asriwi** [comment]
Hi @SRombauts,

I've applied this change to the SQLITECPP_BUILD_EXAMPLES option to cover builds of the executable under MSYS and MINGW.

I'm using the same linking as the examples (given below) for my own project with success.
```
# Link target with pthread and dl for linux
if (UNIX)
    target_link_libraries(SQLiteCpp_example1 pthread)
    if (NOT APPLE)
        target_link_libraries(SQLiteCpp_example1 dl)
    endif ()
elseif (MSYS OR MINGW)
    target_link_libraries(SQLiteCpp_example1 ssp)
endif ()
```

I've tested this on:
- Ubuntu 16.04.1 using g++
- MSYS2 on Windows 10 using g++ and clang (both mingw64)
- MinGW on Windows 10 using g++ (mingw64)
- VS14 on Windows 10
- Travis with the included travis.yml

**Comment by SRombauts** [comment]
Thanks for this!

**Pull request merged**
