### PR TITLE
Add option to check if column is null by name

### PR DESCRIPTION
**Pull request by 4brunu**
While using the library I wanted to check is a column is null, but only found a method that allow to check it by index, so I added one that is similar but check by the column name.

I have also added the tests to it.

### CODE REVIEW

**Comment by SRombauts** [comment]
Thanks @4brunu!

I merged it as-is, but I will rework some of it:
- removing const on isColumnNull() does not seems right
- I believe duplicating code to map indexes to names is not a good idea either

Cheers!

**Comment by 4brunu** [comment]
Hi @SRombauts, sure, no problem at all :)
 
Just to elaborate on some of the decisions:
- I removed const because it was giving a compiler error. I didn't understand why, could you elaborate on that please?
- I tried to do that, but I ended up reverting that because it was resulting in some issues, due to my lack of c++ experience.

Thanks for the amazing library 👍

**Comment by SRombauts** [comment]
The const compiler error was weird: the problem is that we know have two overloaded functions isColumnNull(), one taking an (int), the second one taking a pointer (const char*).
Thus when calling it with zero isColumnNull(0) the compiler has to decide witch one is the best one since 0 is also a nullptr.

There is no problem if the two methods are both const or not const, but there is an error if only one is const: I think that the compiler is not able to decide witch one is the best are they are not real overload...

**Comment by 4brunu** [comment]
Thanks a lot for the explanation :)

**Pull request merged**
