### PR TITLE
Added SQLite header parsing functionality and associated tests

### PR DESCRIPTION
**Pull request by patrick--**
Added header parsing functionality via a `getHeaderInfo()` function. This function reads the first 100 bytes of a SQLite database file and attempts to reconstruct byte groups into the specific header fields within a Header object. Also added tests to demonstrate updating header values via PRAGMA and verifying updated / default header values.

### CODE REVIEW

**Comment by patrick--** [comment]
@SRombauts tell me what you think of this implementation. In the meantime I am looking into getting the tests to pass but still have access to fixed width integer datatypes.

**Comment by SRombauts** [comment]
About the compile error, you can use plain old C type (unsigned char/short/int). Alternatively you could apply your pull request to the slqitcpp-3.x branch that is c++11

**Comment by patrick--** [comment]
@SRombauts I am going to go ahead and replace with plain C types for now so it can be available in master. I'll also open a PR with fixed with support for the C+11 branch. Thanks!

**Comment by SRombauts** [comment]
I left a bunch of comments, but it looks good overall!

**Comment by SRombauts** [comment]
Also don't bother to create a different version for c++11, I don't want that we go an rewrite all just for the sake of it

**Comment by SRombauts** [comment]
And finally, I have just reached 100% unit test code coverage (for what it's worth) so you should test all cases of error

https://coveralls.io/builds/27840818/source?filename=src/Database.cpp

Basically you have to test also with no filename, no file, and wrong file hezder

**Comment by patrick--** [comment]
@SRombauts okay I will get those tests added.

**Comment by patrick--** [comment]
@SRombauts you mentioned leaving some comments? I might be blind, but I'm not seeing those anywhere.

**Comment by SRombauts** [comment]
Sorry, my bad, I didn't know this new review system needed a submit when finished

**Comment by SRombauts** [comment]
That's very good, thanks a lot!

**Pull request merged**
